src/FlaskApp/views/books.py
# Books.py Structure
#
# index()
# This is the route which is the main landing page for displaying all the
# information about the books. It will check the login_session to see if
# the is a user curerntly logged in. If so then will greet that user letting
# them know they are logged in. Else it will greet the Guest.
# add_book()
# It will check if there currently is a user logged in and will redirect
# them to the books page. This is in place if someone tries to manually
# type the address location. If there is a user logged in, then direct
# them to the add_book.jinja2 page. Using the request method POST, it will
# retrieve the information from the form and add it to the database. Then
# will send them back to the main page.
# edit_book(book_id)
# This will retrieve information from the database based on the book_id
# given. It will render that information into a form which could be edited.
# delete_book(book_id)
# This will remove a book form the database. There are features added in the
# delete page which make sure the user wants to delete the book.
# get_language_page(language_id)
# This will only list the books for the chosen language_id

from flask import Blueprint, Flask, render_template, request, redirect, \
                  url_for, jsonify

# Database model
from functools import wraps
from sqlalchemy import desc
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, Books, User, Language
from flask import session as login_session
from app import get_user_id, get_user_info
import random
import string

engine = create_engine('postgresql://catalog:Bradycheated@localhost/catalog')
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
session = DBSession()

books_blueprint = Blueprint('books', __name__)




# Following functions contain querys that are used at multiple instances
# thoughout the blueprint. They are in place so you do not have to changes
# each instance, but make things easier to do.

# Query fucntion that will return the list of books in alphabetical order
def get_books():
    return session.query(Books).order_by(Books.book_title).all()


# Query fuction that will return the languages in the Language model
def get_languages():
    return session.query(Language).all()


# Utilized the functions in app to get the user infromation and uses that
# to display that information in the template. Though the username is
# currently used, this could be helpful for future modifation of information
# that is displayed about the user
def get_current_user():
    return get_user_info(get_user_id(login_session['email']))

# Query function that returns information about the book_id given.
def get_book(book_id):
    return session.query(Books).filter_by(id=book_id).one()


# Query function that returns information about the language_id given.
# This helps to display only books in that language
def get_book_language(language_id):
    return session.query(Books).filter_by(language_id=language_id).all()

# Function returned to the user when they try to modify a book that they did not create
def user_error():
    return "<script>function modifyBook(){ alert('You are only not authoized to "\
           "modify this book. Please create your own book creation.');" \
           "window.location='/books/add/book'}</script><body onload='modifyBook()'>"

@books_blueprint.route('/')
def index():
    if 'username' in login_session:
        return render_template('books.jinja2',
                                books=get_books(),
                                languages=get_languages(),
                                user=get_current_user())
    # This creates a random string of information that will be used in the
    # thrid-party authentication.
    state = ''.join(random.choice(string.ascii_uppercase + string.digits)
                    for x in xrange(32))
    login_session['state'] = state
    return render_template('books.jinja2',
                            books=get_books(),
                            languages=get_languages(),
                            STATE=state)

@books_blueprint.route('/add/book', methods=['GET', 'POST'])
def add_book():
    if request.method == 'POST':
        books = session.query(Books).all()
        # Creating a books object to add to the databse.
        book = Books(book_img=request.form['book_img'],
                     book_title=request.form['book_title'],
                     book_author=request.form['book_author'],
                     book_description=request.form['book_description'],
                     book_url=request.form['book_url'],
                     language_id=request.form['language_id'],
                     user_id=login_session['user_id'])
        session.add(book)
        session.commit()
        return redirect(url_for('books.index'))
    else:
        return render_template('add_book.jinja2',
                                languages=get_languages(),
                                user=get_current_user())

@books_blueprint.route('/delete/<int:book_id>', methods=['GET', 'POST'])
def delete_book(book_id):
    if get_book(book_id) != login_session['user_id']:
        return user_error()
    if request.method == 'POST':
            session.delete(get_book(book_id))
            session.commit()
            return redirect(url_for('books.index',books=get_books()))
    else:
        return render_template('delete_book.jinja2',
                                books=get_book(book_id),
                                languages=get_languages(),
                                user=get_current_user())

@books_blueprint.route('/edit/<int:book_id>', methods=['GET', 'POST'])
def edit_book(book_id):
    if 'username' not in login_session:
        return redirect('/books')
    editedBook = session.query(Books).filter_by(id=book_id).one()
    user = get_current_user()

    if editedBook.user_id != login_session['user_id']:
        return user_error()
    if user.id == editedBook.user_id:
        if request.method == 'POST':
            editedBook.book_img = request.form['book_img']
            editedBook.book_title = request.form['book_title']
            editedBook.book_author = request.form['book_author']
            editedBook.book_description = request.form['book_description']
            editedBook.book_url = request.form['book_url']
            editedBook.language_id = request.form['language_id']

            session.add(editedBook)
            session.commit()
            return redirect(url_for('books.index'))
        else:
            return render_template('edit_book.jinja2',
                                    book=get_book(book_id),
                                    languages=get_languages(),
                                    user=get_current_user())


@books_blueprint.route('/language/<int:language_id>')
def get_language_page(language_id):
    if 'username' not in session:
        render_template('books.jinja2',
                        books=get_book_language(language_id),
                        languages=get_languages())
    return render_template('books.jinja2',
                    books=get_book_language(language_id),
                    languages=get_languages(),
                    user=get_current_user())


# JSON API's to display infromation about the books
@books_blueprint.route('/JSON')
def books_json():
    books = get_books()
    return jsonify(books=[book.serialize for book in books])

@books_blueprint.route('/<int:book_id>/JSON')
def book_json(book_id):
    book = get_book(book_id)
    return jsonify(books=book.serialize)

src/FlaskApp/templates/add_book.jinja2
{% extends 'base.jinja2' %}

{% block content %}

    <script>
    $(document).ready(function(){
        $('span.img-help').mouseenter(function()
            {
                $(".flyout").show();
            });
        $('span.img-help').mouseleave(function()
            {
                $(".flyout").hide();
            });


    });

        // Removes the restrictions on the container size.
        $("#content-container").removeClass("content");

        // Need to display the languages in the select form
        var count = 0;


    </script>
    <h2>Add a book</h2>
    <form method="post" class="form-horizontal" action="#">
        <fieldset id="add_book_menu">
            <div class="flyout">
                <p>
                    Image from Amazon.com webpage. To get, right click on image and scroll to copy image address and paste here.
                </p>
            </div>
           <div class="form-group">
                <label for="inputTitle" class="control-label col-xs-3">Image: <span  class="img-help glyphicon glyphicon-question-sign" aria-hidden="true"></span></label>

                <div class="col-xs-9">
                    <input type="text" class="form-control" name="book_img" placeholder="Image URL">
                </div>
            </div>
            <div class="form-group">
                <label for="inputTitle" class="control-label col-xs-3">Title:</label>
                <div class="col-xs-9">
                    <input type="text" class="form-control" name="book_title" placeholder="Title">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAuthor" class="control-label col-xs-3">Author:</label>
                <div class="col-xs-9">
                    <input type="text" class="form-control" name="book_author" placeholder="Author">
                </div>
            </div>
            <div class="form-group">
                <label for="inputDescription" class="control-label col-xs-3">Desciption:</label>
                <div class="col-xs-9">
                    <textarea type="test" class="form-control" name="book_description" placeholder="Book Description" rows="5"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="inputLanguage" class="control-label col-xs-3">Language:</label>
                <div class="col-xs-9">
                    <select class="form-control" name="language_id" id="select-language">
                        {% for language in languages %}
                        <script>
                            if(count==0)
                            {
                                $("#select-language").append('<option value="' + count + '" selected>{{language.language}}</option>');
                            }
                            else
                            {
                                $("#select-language").append('<option value="' + count + '">{{language.language}}</option>');
                            }
                            count++;
                        </script>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="inputLanguage" class="control-label col-xs-3">Website to buy:</label>
                <div class="col-xs-9">
                    <input type="test" class="form-control" name="book_url" placeholder="http://www.amazon.com/">
                </div>
            </div>
            <div class="form-group">
                 <label for="inputTitle" class="control-label col-xs-3">User Id:</label>
                 <div class="col-xs-9">
                     <input type="text" class="form-control" name="user_id" placeholder="{{user.name}}" disabled>
                 </div>
             </div>
            <div class="text-center">
                <input type="submit" class="btn btn-blue" value="Submit">
                <a href="{{url_for('books.index')}}" class="btn btn-danger" id="cancel"  alt="Cancel">Cancel</a>
            </div>

        </fieldset>
    </form>

    <script>
        $("#add_book_menu").hover(function()
        {
            $('.img-help').show();
        },function()
        {
            $('.img-help').hide();
        });

    </script>
{% endblock %}

src/FlaskApp/templates/aside.jinja2
{% extends 'base.jinja2' %}

{% block aside %}

<aside class="books">

    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand"></span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            {% if 'username' in session %}
              <li><a href="{{url_for()}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
            {% else %}
              <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif%}
            <li>Languages</li>
            <li><a href="#">All</a></li>
            <li><a href="#">C++</a></li>
            <li><a href="#">Java</a></li>
            <li><a href="#">Javascript</a></li>
            <li><a href="#">HTML5</a></li>
            <li><a href="#">PHP</a></li>
            <li><a href="#">Python/Django</a></li>
            <li><a href="#S">Ruby/Rails</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>


    </div>
</aside>
<div class="content container">

{% endblock %}

src/FlaskApp/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Multi-User Blog</title>
		{% include  'html_dependencies.html' %}

	</head>
	<body>
		<div class="container">
			<header class="logo">
				<img class="img-responsive" src="../static/image/logo2.png" alt="">
			</header>

			<div class="content container">
                {% block aside %}

								{% endblock %}

				<div class="content">
					<div class="row">
                        {% block content %}

                        {% endblock %}
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

src/FlaskApp/templates/base.jinja2
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Programming by Readng</title>
        {% include  'html_dependencies.html' %}
    </head>
    <body>

        <script>
            // Generates the language_id for use in the books.get_languages function
            var count = 1;
        </script>
        <div class="container">


        <header class="logo">
            <a href="{{url_for('books.index')}}"><img class="img-responsive" src="{{url_for('static', filename='image/logo2.png')}}" alt=""></a>
        </header>
        <div class="welcome">
            <!-- Displays the Username if it exists in the login_session, and greet then. If
            not the use default greet for Guest -->
            {% if 'username' in session %}
                <p>Welcome, {{user.name}}!</p>
            {% else %}
                <p>Welcome, Guest!</p>
            {% endif %}
        </div>
        <div class="login-bar text-right">
        <!-- If a user has logged in through Google Plus the login_session will return a 'username'.
        Display a link to add a book or to log out. If there is no username in the session
        then show the Google Plus sign in button. -->
                    {% if 'username' in session %}
                        <a class="inner-bar" href="{{url_for('books.add_book')}}">Add Book</a>
                        <a href="{{url_for('gdisconnect')}}"> <span class="glyphicon glyphicon-log-out"></span> Logout</a>
                    {% else %}
                    <!-- GOOGLE PLUS SIGN IN-->


                              <div id="signInButton">
                              <span class="g-signin"
                                data-scope="openid email"
                                data-clientid="844476090512-hq31f24hb62jg757e22im6hnjp513k37.apps.googleusercontent.com"
                                data-redirecturi="postmessage"
                                data-accesstype="offline"
                                data-cookiepolicy="single_host_origin"
                                data-callback="signInCallback"
                                data-approvalprompt="force">
                              </span>
                            </div>

                    <div id="result"></div>

                    <script>
                    function signInCallback(authResult) {
                      if (authResult['code']) {
                        // Hide the sign-in button now that the user is authorized
                        $('#signinButton').attr('style', 'display: none');
                        // Send the one-time-use code to the server, if the server responds, write a 'login successful' message to the web page and then redirect back to the main restaurants page
                        $.ajax({
                          type: 'POST',
                          url: '/gconnect?state={{STATE}}',
                          processData: false,
                          data: authResult['code'],
                          contentType: 'application/octet-stream; charset=utf-8',
                          success: function(result) {
                            // Handle or verify the server response if necessary.
                            if (result) {
                              $('#result').html('Login Successful!</br>'+ result + '</br>Redirecting...')
                             setTimeout(function() {
                              window.location.href = "/books";
                             }, 4000);

                          } else if (authResult['error']) {
                        console.log('There was an error: ' + authResult['error']);
                      } else {
                            $('#result').html('Failed to make a server-side call. Check your configuration and console.');
                             }
                          }

                      }); } }
                    </script>



                    <!--END GOOGLE PLUS SIGN IN -->
                    {% endif%}

        </div>
        <div class="middle">
            <aside class="books">
                <div class="sidebar-nav">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            </button>
                            <span class="visible-xs navbar-brand"></span>
                        </div>
                        <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav" id="language-menu">

                                <li>Languages</li>
                                {% for language in languages %}
                                <script>


                                    $("#language-menu").append("<li><a href='{{url_for('books.get_language_page',language_id=language.id)}}'>{{language.language}}</a></li>");


                                </script>

                                {% endfor %}
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </aside>
            <div class="content" id="content-container">
                {%  block content %}
                {% endblock %}
            </div>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
        </script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->

        <script src="//apis.google.com/js/platform.js?onload=start"> </script>
    </body>
</html>

src/FlaskApp/templates/books.jinja2
{% extends 'base.jinja2' %}

{% block content %}

{% for book in books %}
                    <div class="books-content">
                        <div class="book-img">
                            <img src="{{book.book_img}}" alt="" class="book-img img-responsive">
                        </div>
                        <div class="book-desc ">
                            <div class="book_title">
                                {{book.book_title}}
                            </div>
                            <div class="book_author">
                                <small>by {{book.book_author}}</small>
                            </div>
                            <div class="website">

                                <a href="{{book.book_url}}" class="btn btn-amazon" role="button" target="_blank" alt="buy this book">Buy on Amazon</a>
                            </div>
                            <div class="text-right">
                                {% if 'username' in session %}
                                    {% if user.id == book.user_id %}
                                        [ <a href="{{url_for('books.edit_book',book_id=book.id)}}">Edit</a> | <a href="{{url_for('books.delete_book',book_id=book.id)}}">Delete</a> ]
                                    {% endif %}
                                {% endif %}

                            </div>
                        </div>
                    </div>
{% endfor %}

{% endblock %}

src/FlaskApp/templates/delete_book.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form class="" action="index.html" method="post">
            <legend>Delete a Book</legend>
            <fieldset>
                Deleting a book will permanently delete form teh database.
            </fieldset>
            <fieldset>
                <label class="btn btn-primary">
                    <input type="checkbox"  onchange="document.getElementById('sendNewSms').disabled = !this.checked;"/> Are you sure?
                </label>
            </fieldset>
            <fieldset>
                <input type="submit" name="delete" class="inputButton" id="delete" value=" Delete" disabled="True"/>
                <input type="submit" name="cancel_delete" class="inputButton" id="cancel_delete" value=" Cancel" />

            </fieldset>

        </form>

    </body>
</html>

src/FlaskApp/templates/delete_book.jinja2
{% extends "base.jinja2" %}

{% block content %}

<script>
    $("#content-container").removeClass("content");
</script>

<div class="col-md-12 form-back">
        <form action="{{url_for('books.delete_book',book_id=books.id)}}" method="post">
            <legend>Deleting {{books.title}}</legend>
            <fieldset>
                Deleting {{books.title}} will permanently delete form the database.
            </fieldset>
            <fieldset>
                <label class="confirm-delete">
                    Check box to confirm delete, else click cancel.<br>
                    <input type="checkbox"  id="confirm-delete"/> Are you sure?
                </label>
            </fieldset>
            <fieldset>
                <input type="submit" name="submit" class="btn inputButton" id="delete" value="Delete" disabled/>
                <a href="{{url_for('books.index')}}" class="btn btn-blue" id="cancel"  alt="Cancel">Cancel</a>
            </fieldset>
        </form>
</div>
<script>
var deleteBtn = document.getElementById('delete');
var confirm = document.getElementById('confirm-delete');
var checked = 0;

confirm.onchange = function()
{
    deleteChange();
}

function deleteChange()
{
    if(checked == 0)
    {
        deleteBtn.style.background = "#0f0";
        deleteBtn.style.color = "#000"
        deleteBtn.disabled = false;
        checked = 1;
    }
    else
    {
        deleteBtn.style.background = "#f00";
        deleteBtn.style.color = "gray"
        deleteBtn.disabled = true;
        checked = 0;
    }
}
</script>

{% endblock %}

src/FlaskApp/templates/edit_book.jinja2
{% extends 'base.jinja2' %}


{% block content %}
        <script>
            $(document).ready(function(){
                $('span.img-help').mouseenter(function()
                    {
                        $(".flyout").show();
                    });
                $('span.img-help').mouseleave(function()
                    {
                        $(".flyout").hide();
                    });


            });
            // Removes the content class to correctly use all the space
            $("#content-container").removeClass("content");

            // Uses in the seleect form to correctly display the languages
            var count = 0;
        </script>
        <form method="post" class="form-horizontal" action="#">
            <h2>Edit a book</h2>
            <fieldset>
               <div class="form-group">
                    <label for="inputTitle" class="control-label col-xs-3">Image: <span class="img-help glyphicon glyphicon-question-sign" aria-hidden="true"></span></label>
                    <div class="flyout">
                        <p>
                            Image from Amazon.com webpage. To get, right click on image and scroll to copy image address and paste here.
                        </p>
                    </div>
                    <div class="col-xs-9">
                        <input type="text" class="form-control" name="book_img" value="{{book.book_img}}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputTitle" class="control-label col-xs-3">Title:</label>
                    <div class="col-xs-9">
                        <input type="text" class="form-control" name="book_title" value="{{book.book_title}}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAuthor" class="control-label col-xs-3">Author:</label>
                    <div class="col-xs-9">
                        <input type="text" class="form-control" name="book_author" value="{{book.book_author}}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputDescription" class="control-label col-xs-3">Description:</label>
                    <div class="col-xs-9">
                        <textarea type="test" class="form-control" name="book_description" value="{{book.book_description}}" rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLanguage" class="control-label col-xs-3">Language:</label>
                    <div class="col-xs-9">
                        <select class="form-control" name="language_id" id="select-language" value="{{book.language_id}}">
                            {% for language in languages %}
                            <script>

                                if (count == {{book.language_id}})
                                {
                                    $("#select-language").append('<option value="' + count + '" selected>{{language.language}}</option>');
                                } else
                                {
                                    $("#select-language").append('<option value="' + count + '">{{language.language}}</option>');
                                }

                                count++;
                            </script>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLanguage" class="control-label col-xs-3">Website to buy:</label>
                    <div class="col-xs-9">
                        <input type="test" class="form-control" name="book_url" value="{{book.book_img}}">
                    </div>
                </div>
                <div class="form-group">
                     <label for="inputTitle" class="control-label col-xs-3">User Id:</label>
                     <div class="col-xs-9">
                         <input type="text" class="form-control" name="user_id" placeholder="{{user.name}}" disabled>
                     </div>
                 </div>
                <div class="text-center">
                    <input type="submit" class="btn btn-blue" value="Submit">
                    <a href="{{url_for('books.index')}}" class="btn btn-danger" id="cancel"  alt="Cancel">Cancel</a>
                </div>

            </fieldset>
        </form>
    {% endblock %}

src/FlaskApp/templates/html_dependencies.html
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.css">
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
<link rel="shortcut icon" href="/img/favicon.ico">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
</script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
<!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->

<script src="//apis.google.com/js/platform.js?onload=start"> </script>

src/FlaskApp/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.css">
    <title>Document</title>
    <style>
    div {
        border: 1px solid red;
    }
    </style>

</head>
<body>
    <div class="container">
            <div class="col-md-3">
                <div class="book-img">
                    <img src="{{book.book_img}}" alt="" class="book-img img-responsive">
                </div>
                <div class="book-desc">
                    <div class="book_title">
                        Learn Python the Easy Way
                    </div>
                    <div class="book_author">
                        <small>by Zed C. Shaw</small>
                    </div>
                    <div class="website">

                        <a href="{{book.book_url}}" class="btn btn-amazon" role="button" target="_blank" alt="buy this book">Buy on Amazon</a>
                    </div>
                    <div class="text-right">
                        {% if 'username' in session %}
                            {% if user.id == book.user_id %}
                                [ <a href="{{url_for('books.edit_book',book_id=book.id)}}">Edit</a> | <a href="{{url_for('books.delete_book',book_id=book.id)}}">Delete</a> ]
                            {% endif %}
                        {% endif %}

                    </div>

            </div>

        </div>  <!--  END DIV -->

    </div>

</body>
</html>